### ISSUE TITLE
Unit status change

### ISSUE THREAD

**Issue by SoSA-ConnorG** [CADvanced/CADvanced#6]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
The ability for units to update their own status, preferably in game, without the need of Dispatcher permissions.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by Chuckatron** [comment]
This has now been migrated to the CADvanced Trello board https://trello.com/b/8x3eP6uK/cadvanced

Closing
